{
  "openapi": "3.0.0",
  "info": {
    "title": "Points Records back-end documentation",
    "description": "This is a API of points records",
    "version": "1.0.0",
    "contact": {
      "email": "andremarcos967@gmail.com"
    }
  },
  "paths": {
    "/api/v1/users": {
      "post": {
        "tags": ["User"],
        "summary": "Create a user",
        "description": "Create a new user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "required": true
                  },
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  },
                  "confirmPassword": {
                    "type": "string",
                    "required": true
                  },
                  "role": {
                    "type": "string",
                    "required": true
                  }
                }
              },
              "example": {
                "name": "admin",
                "email": "admin@point.com.br",
                "password": "12345678",
                "confirmPassword": "12345678",
                "role": "admin"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "number"
                        },
                        "name": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "role": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "message": "Usuário cadastrado com sucesso!",
                  "user": {
                    "id": 1,
                    "name": "admin",
                    "email": "admin@point.com.br",
                    "role": "admin"
                  }
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Email inválido"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/login": {
      "post": {
        "tags": ["User"],
        "summary": "Create a session",
        "description": "Create a new session",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  }
                }
              },
              "example": {
                "email": "admin@point.com.br",
                "password": "12345678"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "response": {
                      "type": "object",
                      "properties": {
                        "user": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "number"
                            },
                            "name": {
                              "type": "string"
                            },
                            "email": {
                              "type": "string"
                            },
                            "role": {
                              "type": "string"
                            }
                          }
                        },
                        "token": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "message": "Login realizado com sucesso!",
                  "response": {
                    "user": {
                      "id": 1,
                      "name": "admin",
                      "email": "admin@point.com.br",
                      "role": "admin"
                    },
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njk3MTAyMTksImV4cCI6MTY2OTc5NjYxOSwic3ViIjoiMiJ9.2Iasuel923K2v0E0f52D-MNwNpiyYL_W2rIOHIpbRp8"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Email ou senha incorreto"
                }
              }
            }
          },
          "400": {
            "description": "bad request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Email ou senha incorreto"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/point-records/": {
      "get": {
        "tags": ["Point Record"],
        "summary": "Create point record",
        "description": "Create a new point record",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "point": {
                      "id": {
                        "type": "number"
                      },
                      "user": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "name": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "role": {
                            "type": "string"
                          }
                        }
                      },
                      "time_registered": {
                        "type": "string"
                      }
                    }
                  }
                },
                "example": {
                  "message": "Ponto registrado com sucesso!",
                  "point": {
                    "id": 1,
                    "user": {
                      "id": 1,
                      "name": "admin",
                      "email": "admin@point.com.br",
                      "role": "admin"
                    },
                    "time_registered": "2022-11-29T07:51:27.877Z"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Usuário não encontrado"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/point-records/list": {
      "get": {
        "tags": ["Point Record"],
        "summary": "List point records",
        "description": "Create all  point records",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "pointRecords": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "user": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "name": {
                                "type": "string"
                              },
                              "email": {
                                "type": "string"
                              },
                              "role": {
                                "type": "string"
                              }
                            }
                          },
                          "time_registered": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "message": "Lista de registro de pontos!",
                  "pointRecords": [
                    {
                      "id": 1,
                      "user": {
                        "id": 1,
                        "name": "usuário",
                        "email": "teste@gmail.com",
                        "role": "colaborador"
                      },
                      "time_registered": "2022-11-25T08:55:41.014Z"
                    },
                    {
                      "id": 2,
                      "user": {
                        "id": 2,
                        "name": "usuário",
                        "email": "teste2@gmail.com",
                        "role": "colaborador"
                      },
                      "time_registered": "2022-11-25T08:56:47.801Z"
                    }
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Acesso negado"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/point-records/user": {
      "get": {
        "tags": ["Point Record"],
        "summary": "List point records by user",
        "description": "Create all  point records by user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "pointRecords": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "number"
                          },
                          "user": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "number"
                              },
                              "name": {
                                "type": "string"
                              },
                              "email": {
                                "type": "string"
                              },
                              "role": {
                                "type": "string"
                              }
                            }
                          },
                          "time_registered": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "message": "Lista de registro de pontos do usuário!",
                  "pointRecords": [
                    {
                      "id": 1,
                      "user": {
                        "id": 1,
                        "name": "usuário",
                        "email": "teste@gmail.com",
                        "role": "colaborador"
                      },
                      "time_registered": "2022-11-25T08:55:41.014Z"
                    },
                    {
                      "id": 2,
                      "user": {
                        "id": 1,
                        "name": "usuário",
                        "email": "teste@gmail.com",
                        "role": "colaborador"
                      },
                      "time_registered": "2022-11-25T08:56:47.801Z"
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string"
                    },
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "status": "error",
                  "message": "Usuário não encontrado"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
